#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep bspswallow || bspswallow &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.505
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#c0caf5"
bspc config normal_border_color "#292e42"
bspc config presel_feedback_color "#c0caf5"

bspc rule -a Pavucontrol state=floating
bspc rule -a Logseq desktop=^7

picom &
$HOME/.config/feh/.fehbg &
sxhkd -m1 &
polybar &
logseq &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync' &
