#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.505
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#a9b1d6"
bspc config normal_border_color "#262838"
bspc config presel_feedback_color "#a9b1d6"

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Nemo state=floating
bspc rule -a Gedit state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Timeshift state=floating
bspc rule -a firefox:Places state=floating

$HOME/.fehbg &
picom --experimental-backends &
polybar -r &
timeshift &
$HOME/.config/scripts/monocle-0-1
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
sxhkd -m1 &
